name: AI Code Review Bot

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Static Analysis
        run: scripts/static_analysis.sh

      - name: AI Code Review
        run: python scripts/ai_review.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

